### ISSUE TITLE
Error response from daemon: path /home/adexandros/projects/test/.reward/nginx is mounted on / but it is not a shared mount.

### ISSUE THREAD

**Issue by adexandros** [rewardenv/reward#11]
Hi @janosmiko,

I am setting up reward on a new device with WSL2 and using the native linux reward installation inside the host; everything looked good until I tried to initialise an environment for a test project, getting the following error:
`Error response from daemon: path /home/adexandros/projects/test/.reward/nginx is mounted on / but it is not a shared mount.`

nginx seems like the only container unable to start due to the above, do have any hint for this?

thanks

**Comment by janosmiko** [comment]
Hi @adexandros !

Thank you for the report and the answer as well.

This seems to be the problem here:
https://stackoverflow.com/questions/68273745/how-to-make-a-mount-shared-in-docker

I think in docker-compose v2 there's a breaking change for this (and there are others as well which I will work on in the next 1-2 weeks).
Anyway, I just updated Reward.
Could you verify please if it's working now in Reward v0.2.11-beta?
