### ISSUE TITLE
Request for OpenSearch as optional package

### ISSUE THREAD

**Issue by hafeez3000** [rewardenv/reward#22]
https://support.magento.com/hc/en-us/articles/4419942355725-Switching-to-OpenSearch-for-Adobe-Commerce-on-Cloud-2-4-4

**Comment by janosmiko** [comment]
Hi @hafeez3000 !

Thanks for opening this feature request. 
This is definitely on the map, I think I will add it to Reward in the next 1-2 days. Stay tuned!

**Comment by janosmiko** [comment]
I added OpenSearch to the latest release of Reward. 
As it installs Magento 2.4.4 as the default Magento version, I configured it to use OpenSearch instead of Elasticsearch by default, but it is possible to go back to Elasticsearch (to support older versions of Magento). 

=> So now the default search engine is OpenSearch but we still support Elasticsearch.

I also added OpenSearch Dashboards (which is the fork of Kibana), which can be enabled per environment.
https://rewardenv.readthedocs.io/en/latest/customization/search.html
